# -*- coding: utf-8 -*-
"""annotation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nYsvEA2NzFeQ3a0mdMayrKT31HIOCCQT
"""

import pandas as pd
from transformers import pipeline

df = pd.read_csv("file.csv", encoding='latin-1')
comments = df["@commentaires: {"].tolist()

classifier = pipeline("zero-shot-classification", model="MoritzLaurer/mDeBERTa-v3-base-mnli-xnli")

sentiment_labels = ["positif", "négatif", "neutre"]
problem_labels = ["problème réseau", "service client", "facturation", "internet", "offres commerciales", "infrastructure", "réactivité", "autre"]

results = []

for comment in comments:
    sentiment_result = classifier(comment, sentiment_labels, multi_label=False)
    sentiment = sentiment_result["labels"][0]
    problem = ""

    if sentiment == "négatif":
        problem_result = classifier(comment, problem_labels, multi_label=True)
        problem = problem_result["labels"][0]

    results.append({
        "commentaire": comment,
        "sentiment": sentiment,
        "probleme": problem if sentiment == "négatif" else "N/A"
    })

pd.DataFrame(results).to_csv("resultats_analyse.csv", index=False)
print("Analyse terminée")